### ISSUE TITLE
Customhostnames -> Tutorial has small mistake with wording

### ISSUE THREAD

**Issue by Laurisade** [mxroute/mxdocs#10]
https://mxroutedocs.com/branding/customhostnames/

It works wonderfully, but I have noticed that some of the information provided is slightly outdated.

**Current text:** From there, click on Free & automatic certificate from Let’s Encrypt. It looks like this:
**Should be:** From there, click on Get automatic certificate from ACME Provider. It looks like this:

**Comment by mxroute** [comment]
Good catch! I need to update the screenshot later, but the text is updated for now.
