### ISSUE TITLE
The dates on the help pages are incorrect

### ISSUE THREAD

**Issue by halfwit** [mxroute/mxdocs#23]
While navigating the website, I noticed each post date showed "Updated 01 Jan, 0001"
<img width="1232" alt="Screenshot 2023-09-24 at 10 17 17" src="https://github.com/mxroute/mxdocs/assets/11841517/5080303f-1b43-4cb9-a0d7-4f993c1077a3">

On those pages, the frontmatter doesn't have a `date` entry. When I run the site locally, adding the date field to the frontmatter ( for example, `date: 2023-02-12T00:29:14-08:00`) yields the correct results 
<img width="1232" alt="Screenshot 2023-09-24 at 10 23 02" src="https://github.com/mxroute/mxdocs/assets/11841517/90125357-52bb-48b8-b837-eb0c85a15421">

**Comment by mxroute** [comment]
Resolved with https://github.com/mxroute/mxdocs/pull/25
