### ISSUE TITLE
update some links to the new mxroutedocs site

### ISSUE THREAD

**Issue by feinedsquirrel** [mxroute/mxdocs#3]
Going through the documentation to get everything set up, I noticed that some links point to mxroutehelp. If I'm not mistaken, that is an "old" site?
One in particular, https://mxroutedocs.com/directadmin/defaultwebmail/ includes a link to the "Custom Webmail ... Domain" on the "old" site. That same page exists in the new docs site. The new iteration is missing the last screenshot image, otherwise, the wording has been updated a little but is overall the same page.

I'm happy to fork and submit a pull request with those changes, as well as some typos throughout, if you would like me to. Let me know.

Edit:
Would also be nice to have a short explanation of the difference between "delete" and "purge" on the 'Email Accounts' page. If the answer to this is in there, I haven't found it. I re-read through the "DirectAdmin", "general", and "troubleshooting" directories.

**Comment by mxroute** [comment]
I think I resolved this and forgot to close it out
